name = "boring-jobs"
version = "<%= package.version %>"
description = "On-Chain Decentralized Job Board"
keywords = [
  "boringjobs",
  "job board",
  "decentralized",
  "ethereum",
  "solidity",
  "truffle",
  "dapp",
  "blockchain",
  "smart contract",
]

[contract.JobBoard]
artifact = "JobBoard"
